In [21]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura em metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [22]:
lista_de_centimetros = list(range(170, 190, 5))

In [24]:
altura_em_centimetros = np.array(lista_de_centimetros)
for k, v in enumerate(altura_em_centimetros):
    print(f'A {k +1}ª altura em cm é: {v}cm')

A 1ª altura em cm é: 170cm
A 2ª altura em cm é: 175cm
A 3ª altura em cm é: 180cm
A 4ª altura em cm é: 185cm


In [25]:
altura_em_metros = altura_em_centimetros / 100

for k, v in enumerate(altura_em_metros):
    print(f'A {k +1}ª altura em metros é: {v}m')

A 1ª altura em metros é: 1.7m
A 2ª altura em metros é: 1.75m
A 3ª altura em metros é: 1.8m
A 4ª altura em metros é: 1.85m


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [27]:
lista_pesos = [70, 75, 80, 85]
# seu código aqui
pesos = np.array(lista_pesos)
for k, v in enumerate(pesos):
    print(f'{k +1}º peso: {v}kg')

1º peso: 70kg
2º peso: 75kg
3º peso: 80kg
4º peso: 85kg


In [38]:
# calcule o IMC dessas pessoas
imc = pesos / altura_em_metros**2
for k, v in enumerate(imc):
    print(f'{k +1}º peso: {v}kg')

1º peso: 24.221453287197235kg
2º peso: 24.489795918367346kg
3º peso: 24.691358024691358kg
4º peso: 24.835646457268076kg


In [39]:
for c in range(0, len(imc)):
    print(f'A {c+1}ª pessoa possui o peso de {pesos[c]}kg, a altura de {altura_em_metros[c]}m e o IMC de {round(imc[c], 2)}')

A 1ª pessoa possui o peso de 70kg, a altura de 1.7m e o IMC de 24.22
A 2ª pessoa possui o peso de 75kg, a altura de 1.75m e o IMC de 24.49
A 3ª pessoa possui o peso de 80kg, a altura de 1.8m e o IMC de 24.69
A 4ª pessoa possui o peso de 85kg, a altura de 1.85m e o IMC de 24.84


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [70]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]


In [75]:
nd_finaceitos = np.array(dados_financeiros)
print(f'Os dados do financeiro: \n{nd_financeiros}')

Os dados do financeiro: 
[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [76]:
nd_financeiros = nd_financeiros.transpose()
print(f'Os dados transposto do financeiro: \n{nd_financeiros}')

Os dados transposto do financeiro: 
[[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  7000]
 [10000  5000 16000]]


In [77]:
endividamento_total = (nd_financeiros[:,0] + nd_financeiros[:,1]) / nd_financeiros[:,2]
print(f'O endividamento total: \n{endividamento_total}')

O endividamento total: 
[0.66666667 0.90909091 0.57142857 0.9375    ]


In [78]:
nd_financeiros[2,2] = 1000
print(f'Os dados do financeiro: \n{nd_financeiros}')


Os dados do financeiro: 
[[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  1000]
 [10000  5000 16000]]


In [79]:
endividamento_total = (nd_financeiros[:,0] + nd_financeiros[:,1]) / nd_financeiros[:,2]
print(f'O endividamento total: \n{endividamento_total}')

O endividamento total: 
[0.66666667 0.90909091 4.         0.9375    ]


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [80]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [81]:
# i) crie o objeto bool_zero através do operador ==
bool_zero = poi == 0
bool_zero

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [82]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)
sum(bool_zero)

6

In [83]:
# iii) utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero
poi_nao_zero = poi[~bool_zero]
poi_nao_zero

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 3, 3, 2, 8, 2, 3, 3, 3, 4, 4, 2, 6, 6,
       3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3, 2, 2, 3,
       6, 2, 2, 4, 3, 5, 2, 5, 3, 2, 1, 1, 4, 4, 4, 6, 2, 4, 1, 2, 5, 5,
       3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 4, 4, 6, 1, 3, 4, 2, 5, 4, 5,
       5, 3, 4, 6, 8, 2])